### ISSUE TITLE
`boot_steps` fail to expand `{{ .HTTPIP }}` and `{{ .HTTPPort }}`

### ISSUE THREAD

**Issue by jacob-carlborg** [hashicorp/packer-plugin-qemu#109]
#### Overview of the Issue

If `{{ .HTTPIP }}` or `{{ .HTTPPort }}` are used in `boot_steps` they will not be expanded. When Packer is supposed to type the IP address or port, it instead outputs `<no value>`.

Looks like I missed something when I implemented `boot_steps` in https://github.com/hashicorp/packer-plugin-qemu/pull/103.

#### Reproduction Steps

Use `{{ .HTTPIP }}` or `{{ .HTTPPort }}` in `boot_steps`.

### Plugin and Packer version

`boot_steps` was added in packer-plugin-qemu 1.0.7.

### Simplified Packer Buildfile

Partial build file of NetBSD:

```terraform

boot_steps = [
  ["a<enter><wait5>", "Installation messages in English"]
  ["a<enter><wait5>", "Keyboard type: unchanged"],
  ["e<enter><wait5>", "Utility menu"],
  ["a<enter><wait5>", "Run /bin/sh"],

  ["{{.HTTPIP}}:{{.HTTPPort}}"],
]
```

**Comment by lbajolet-hashicorp** [comment]
Hi @jacob-carlborg,

Sorry I missed that one, I'm surprised it happens as it would be the `interpolate.Render` call that takes care of that, but based on your experience, it looks like something else's missing.

I'm also able to replicate the problem locally, so it does look like a bug to fix.

I'll investigate, once I figure out what's happening and I can submit a fix, we can release a new version of the plugin.

Thanks for signalling this to us!

**Comment by lbajolet-hashicorp** [comment]
Well that was an easier fix than expected :)

We'll release v1.0.8 of the plugin, either today or Monday at the latest, you should have this fixed on the latest main if you want to spin a test @jacob-carlborg.

Thanks again for signalling this bug!

**Comment by jacob-carlborg** [comment]
@lbajolet-hashicorp Awesome, thanks. I've been banging my head against the wall with this bug for a while now.

**Comment by jacob-carlborg** [comment]
@lbajolet-hashicorp I've tried your fix and can confirm it's now working. Thanks again.
