### ISSUE TITLE
Running Windows VM on mac M2 stuck at Start boot option

### ISSUE THREAD

**Issue by yimpng** [hashicorp/packer-plugin-qemu#181]
I have done all the steps required conversion of vhdx to cowq2 gave the correct path directory as well as assigned enough memory allocation. However while loading, I can go into the boo tmenu by pressing F10 and ESC but the loading screen is stuck indefinitely as the screenshot denotes. Please help 
![Screenshot 2024-09-12 at 2 38 24 AM](https://github.com/user-attachments/assets/005912c0-f1fe-43d6-8d07-10d982316a68)

**Comment by lbajolet-hashicorp** [comment]
Hi @yimpng,

This tracker is mostly aimed at maintaining Packer, and as such issues are mostly reserved for bug reports or feature requests, for questions, we will try to respond to the best of our abilities, but usage questions like yours are better suited to our [discuss forums](https://discuss.hashicorp.com/c/packer/23) where the users community is more active, and where they will be more likely to respond to your question.

I will close this issue now, and encourage you to post your question here, but if I may I would suggest you share a template or the commands you run so someone will be able to help, as in the current state it's hard to understand what you tried, and what may be the problem.

Thanks!
