### ISSUE TITLE
cd_content mentioned in docs but not in packer binary in QEMU builder

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-qemu#45]
_This issue was originally opened by @gzzchh in https://github.com/hashicorp/packer/issues/11289 and has been migrated to this repository. The original issue description is below._

---
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

current packer binary could not recognize cd_content in QEMU builder
![image](https://user-images.githubusercontent.com/17796830/134964419-ceb36926-c360-4707-8eb2-529dea3c53a1.png)

build it is mentioned in docs
![image](https://user-images.githubusercontent.com/17796830/134965108-39b699df-f6b9-4a1a-9941-1efbdbf8a080.png)

#### Reproduction Steps

use any Packer 1.7.5 to build image with QEMU and cd_content
![image](https://user-images.githubusercontent.com/17796830/134964591-563c0cd1-8d4a-4baf-a49b-21f32da10e82.png)

### Packer version

1.7.5 or 1.7.6

![image](https://user-images.githubusercontent.com/17796830/134964727-a48cc185-a6bb-43ca-ae3c-02e408a215b8.png)

### Simplified Packer Buildfile

```
source "qemu" "debian_10_general" {
  # 为了获取更好的写性能这里不使用缓存
  disk_cache         = "none"
  format             = "qcow2"
  disk_compression   = true
  disk_discard       = "unmap"
  disk_detect_zeroes = "on"
  # 这次尝试用云镜像
  disk_image       = true
  use_backing_file = false
  # 准备 cloud-init 光盘
  cd_files = [
    "${path.root}/cloud-init/meta-data",
  ]
 # Here
  cd_content = {
    "user-data" = templatefile("${path.root}/cloud-init/user-data", {
      "ssh_public_key" = data.sshkey.install.public_key
    })
  }
  cd_label = "cidata"
}
```

### Operating system and Environment details

Fedora 34 x86_64

### Log Fragments and crash.log files

![image](https://user-images.githubusercontent.com/17796830/134964972-48cf00bc-55cd-42a7-8846-9c572f9f97e6.png)

**Comment by nywilken** [comment]
Hi there @gzzchh version 1.0.1 was released today with the needed changes for the cd_content configuration argument. Please update your build template to pull in the latest version of the plugin and retest your configuration.

```
packer {
  required_plugins {
    qemu = {
      version = ">= 1.0.1"
      source  = "github.com/hashicorp/qemu"
    }
  }
}
```
I'm going to close this issue as I believe it has been resolved. But if you are running into issues with the latest release please drop a comment on this thread and we will gladly reopen. Cheers!
