### ISSUE TITLE
use_backing_file is broken with QEMU 6.1

### ISSUE THREAD

**Issue by quyse** [hashicorp/packer-plugin-qemu#47]
#### Overview of the Issue

Apparently in QEMU 6.1 `qemu_img` cannot be invoked with backing file, but without specifying format of the backing file. See https://qemu.readthedocs.io/en/latest/about/removed-features.html#qemu-img-backing-file-without-format-removed-in-6-1

As a result, Packer's `use_backing_file: true` is broken with QEMU 6.1.

The workaround is to use `qemu_img_args` in builder config to add necessary argument for qemu-img:
```
"qemu_img_args": {
  "create": ["-F", "qcow2"]
}
```

Despite the workaround existing, should be worth fixing in the packer-plugin-qemu itself.

#### Reproduction Steps

Run packer build with QEMU builder and backing file (`use_backing_file: true`). Use QEMU 6.1 or later. The build results in the error `QemuImg error: qemu-img: build/packer-qemu: Backing file specified without backing format` (see log below).

The same config works when used with QEMU 6.0 or earlier, where qemu-img only issues a deprecation warning.

### Plugin and Packer version

Packer v1.7.6

### Simplified Packer Buildfile

```
{
  "builders": [
    {
      "communicator": "winrm",
      "cpus": "{{ user `cpus` }}",
      "disk_image": true,
      "disk_size": "256G",
      "headless": true,
      "iso_checksum": "none",
      "iso_url": "<backing disk image>",
      "memory": 4096,
      "output_directory": "build",
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "shutdown_timeout": "15m",
      "skip_compaction": true,
      "skip_resize_disk": true,
      "type": "qemu",
      "use_backing_file": true,
      "winrm_password": "vagrant",
      "winrm_timeout": "30m",
      "winrm_username": "vagrant"
    }
  ]
}
```

### Operating system and Environment details

Packer/qemu from nixkgs, on top of Arch Linux x64.

### Log Fragments and crash.log files

Relevant part of the log:

```
2021/10/05 07:54:38 packer-builder-qemu plugin: [INFO] Creating disk with Path: build/packer-qemu and Size: 256G
2021/10/05 07:54:38 packer-builder-qemu plugin: Executing qemu-img: []string{"create", "-f", "qcow2", "-b", "/nix/store/rkdhflwh9nf201g3pgpx8ysgnvxrv7ci-windows-2019", "build/packer-qemu", "256G"}
[1;32m==> qemu: Creating required virtual machine disks[0m
2021/10/05 07:54:38 packer-builder-qemu plugin: stdout:
2021/10/05 07:54:38 packer-builder-qemu plugin: stderr: qemu-img: build/packer-qemu: Backing file specified without backing format
2021/10/05 07:54:38 packer-builder-qemu plugin: Detected format of qcow2.
==> qemu: Detected format of qcow2.[0m
[1;31m==> qemu: Error creating hard drive: QemuImg error: qemu-img: build/packer-qemu: Backing file specified without backing format
==> qemu: Detected format of qcow2.[0m
[1;32m==> qemu: Deleting output directory...[0m
Detected format of qcow2.[0m
==> Wait completed after 6 milliseconds 446 microseconds
2021/10/05 07:54:38 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2021/10/05 07:54:38 machine readable: qemu,error []string{"Error creating hard drive: QemuImg error: qemu-img: build/packer-qemu: Backing file specified without backing format\nDetected format of qcow2."}
Detected format of qcow2.
```

**Comment by odra** [comment]
Apologies, I know this issue is already closed but I totally missed that :( 

I just wanted to thank you, that worked for me.
