### ISSUE TITLE
Change the default CPU topology given to QEMU when numCpus > 1

### ISSUE THREAD

**Issue by Eijebong** [hashicorp/packer-plugin-qemu#55]
#### Overview of the Issue

When creating a QEMU virtual machine with more than one cpu, (`"cpus": "8",` in the given json file), packer will spawn QEMU with the following argument: `-smp cpus=8,sockets=8` which is equivalent to exposing 8 physical 1 core CPUs to the virtual machine. While this is fine for most operating systems, windows does not like that at all. On a non workstation installation, it will cap the CPU number to 2 which means you try giving it as many CPUs as you want, it will always see 2 of them. 

#### Reproduction Steps

Use the QEMU provider with `"cpus": "8",`.

### Packer version

Packer v1.7.8

### Simplified Packer Template

https://github.com/StefanScherer/packer-windows/blob/da1d60b0cd97ff7a9bdeb67a7612ec7c8169869b/windows_10.json and just changes cpus to 8.

###  References

The line that sets up the CPU topology is here. https://github.com/hashicorp/packer-plugin-qemu/blob/e47a7a53d628a46f5257bd92ce4d262e67a856c5/builder/qemu/step_run.go#L149

Same issue in virt-manager: https://github.com/virt-manager/virt-manager/issues/155

### Possible resolution

Change to `-smp 8,sockets=1,cores=8` by default

**Comment by lbajolet-hashicorp** [comment]
Hi @Eijebong,

Sorry for answering that late, but as the saying goes, better late than never!

I've opened PR #94 that changes the combination of options available to change the SMP configuration for spawning qemu, I'm still working on testing this on a proper image, but from the looks of the unit tests I added, this should either solve your problem automatically if you're running qemu v6.2+, or at least give you options to specify that you want a SMP machine with 1 socket and 8 cores through the `sockets` and `cores` options.

If you want to test it, you may build the project manually and install it, when it's approved and my tests confirm the behaviour is what we expected, I'll merge this. After that, the next version of the plugin will contain those new options and you can use it officially on your configs.

Thanks for bringing this to our attention, and sorry again for leaving your issue in limbo for so long.
